import AntdProvider from "@/components/AntdProvider";
import "@/styles/globals.css";
import { TRPCReactProvider } from "@/trpc/react";
import { type Lang } from "@/types";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

type Props = { children: React.ReactNode; params: { lang: Lang } };

export default function RootLayout({ children, params }: Props) {
  return (
    <html lang={params.lang}>
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <AntdProvider>
            <main>{children}</main>
          </AntdProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
